### ISSUE TITLE
[Epic#2] 사용자는 코드를 동시에 편집 가능하다.

### ISSUE THREAD

**Issue by dididy** [CodeSoom/project-react-1-dididy#21]
- 코드 에디터를 추가한다.
- WebRTC를 이용해 참여자 모두 동시에 코드 편집을 가능하도록 한다.
  - 편집중인 각각의 라인은 lock이 걸리도록 한다.

## 완료 조건
- [x] 코드 에디터(monaco editor)를 적용한다.
  - [ ] 코드 에디터에 맞는 적절한 UI를 구현한다.
- [x] WebRTC([simple peer](https://github.com/feross/simple-peer#readme))를 이용한 동시 코드 편집 기능 구현한다.
  - [x] 기존 로직에 data channel 추가
  - [x] 편집 중인 라인에 대한 Lock 기능 구현

## 관련 이슈
N/A

## Reference
- [backlog](https://docs.google.com/spreadsheets/d/1TfKpYk_k9cbGW7E_2wsl9niQFMgingPHzyYeC4GnEFw/edit?usp=sharing)
- [wireframe](https://docs.google.com/presentation/d/1BwK2fehkiap48LlRPOYUpiRAIoETkyN3QE-lp2v6GSU/edit?usp=sharing)
