### ISSUE TITLE
[Epic#1] 사용자는 화상통화를 할 수 있다.

### ISSUE THREAD

**Issue by dididy** [CodeSoom/project-react-1-dididy#6]
- 화상 통화 기능을 구현한다.
- 서버를 통해 사용자끼리 매칭할 수 있도록 한다.

## 완료 조건
- [x] Main UI 를 구현한다. - 3시간 소요
- [x] WebRTC([simple peer](https://github.com/feross/simple-peer#readme))를 이용한 화상 연결 구성 
  - [x] socket.io 서버를 이용해 특정 유저 간 매칭 - 4시간 소요
  - [x] TDD로 redux 적용 - 5시간 소요
- [x] GitHub Action을 이용해 lint, test 검사 및 배포환경 구성 - 6시간 소요
  - [netlify](https://pair-with.netlify.app/) / [heroku](https://pair-with.herokuapp.com/)

## 관련 이슈
N/A

## Reference
- [backlog](https://docs.google.com/spreadsheets/d/1TfKpYk_k9cbGW7E_2wsl9niQFMgingPHzyYeC4GnEFw/edit?usp=sharing)
- [wireframe](https://docs.google.com/presentation/d/1BwK2fehkiap48LlRPOYUpiRAIoETkyN3QE-lp2v6GSU/edit?usp=sharing)
